
logging:
  level: info
server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.24.201:3306/db_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  type-aliases-package: com.example.pojo
#spring:
#  thymeleaf:
#            prefix: classpath:/templates/
#            suffix: .html

